/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.NGO.NGO;
import Business.NGO.NGODirectory;
import Business.Role.NgoRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.DonorRole.DonorProfilePanel;

/**
 *
 * @author aravindasagiraju
 */
public class AddNGOPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddNGOPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    NGODirectory ngod;
    UserAccountDirectory uad;
    public AddNGOPanel(JPanel userProcessContainer, EcoSystem ecosystem) throws IOException {
        initComponents();

//        imageLbl.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//        imageLbl.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//        imageLbl.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//
//        Image img = ImageIO.read(getClass().getResource("/Images/blurbg.jpeg"));
//
//        Image newimg = img.getScaledInstance(userProcessContainer.getWidth(), userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
//        imageLbl.setIcon(new ImageIcon(newimg));

          this.userProcessContainer = userProcessContainer;
          this.ecosystem = ecosystem;
          if(ecosystem.getNgoDir() == null){
              ecosystem.setNgoDir(new NGODirectory());
          }
          
          setBG();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddNGOTitle = new javax.swing.JLabel();
        lblNGOname = new javax.swing.JLabel();
        txtNGOname = new javax.swing.JTextField();
        lblNGOPhno = new javax.swing.JLabel();
        txtNGOPhno = new javax.swing.JTextField();
        lblNGOAdd = new javax.swing.JLabel();
        txtNGOAdd = new javax.swing.JTextField();
        lblNGOCity = new javax.swing.JLabel();
        txtNGOCity = new javax.swing.JTextField();
        lblNGOState = new javax.swing.JLabel();
        txtNGOState = new javax.swing.JTextField();
        lblNGOZip = new javax.swing.JLabel();
        txtNGOZip = new javax.swing.JTextField();
        lblNGOAgent = new javax.swing.JLabel();
        txtNGOAgent = new javax.swing.JTextField();
        lblNGOAgentuname = new javax.swing.JLabel();
        txtNGOAgentuname = new javax.swing.JTextField();
        lblNGOpwd = new javax.swing.JLabel();
        txtNGOpwd = new javax.swing.JTextField();
        lblNGOcopwd1 = new javax.swing.JLabel();
        txtNGOcopwd1 = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblNGOid = new javax.swing.JLabel();
        txtNGOid = new javax.swing.JTextField();
        lblNGOid2 = new javax.swing.JLabel();
        lblNGOname1 = new javax.swing.JLabel();
        lblNGOPhno1 = new javax.swing.JLabel();
        lblNGOZip1 = new javax.swing.JLabel();
        lblNGOAdmin1 = new javax.swing.JLabel();
        lblNGOpwd2 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        LabelImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddNGOTitle.setFont(new java.awt.Font("Georgia", 1, 29)); // NOI18N
        lblAddNGOTitle.setForeground(new java.awt.Color(51, 153, 255));
        lblAddNGOTitle.setText("Add NGO");
        add(lblAddNGOTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        lblNGOname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOname.setText("NGO Name :");
        add(lblNGOname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        txtNGOname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOname.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOnameFocusLost(evt);
            }
        });
        add(txtNGOname, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 137, -1));

        lblNGOPhno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOPhno.setText("Phone Number :");
        add(lblNGOPhno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        txtNGOPhno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOPhno.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOPhno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOPhnoFocusLost(evt);
            }
        });
        add(txtNGOPhno, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 137, -1));

        lblNGOAdd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOAdd.setText("Address :");
        add(lblNGOAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        txtNGOAdd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOAdd.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNGOAddActionPerformed(evt);
            }
        });
        add(txtNGOAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 137, -1));

        lblNGOCity.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOCity.setText("City :");
        add(lblNGOCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        txtNGOCity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOCity.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtNGOCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 137, -1));

        lblNGOState.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOState.setText("State :");
        add(lblNGOState, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        txtNGOState.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOState.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtNGOState, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 137, -1));

        lblNGOZip.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOZip.setText("Zipcode :");
        add(lblNGOZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        txtNGOZip.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOZip.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOZip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOZipFocusLost(evt);
            }
        });
        add(txtNGOZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 137, -1));

        lblNGOAgent.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOAgent.setText("NGO Agent :");
        add(lblNGOAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        txtNGOAgent.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOAgent.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOAgent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOAgentFocusLost(evt);
            }
        });
        add(txtNGOAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 137, -1));

        lblNGOAgentuname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOAgentuname.setText("NGO Agent Username :");
        add(lblNGOAgentuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, -1));

        txtNGOAgentuname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOAgentuname.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtNGOAgentuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 137, -1));

        lblNGOpwd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOpwd.setText("Password :");
        add(lblNGOpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, -1, -1));

        txtNGOpwd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOpwd.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtNGOpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 137, -1));

        lblNGOcopwd1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOcopwd1.setText("Confirm Password :");
        add(lblNGOcopwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, -1, -1));

        txtNGOcopwd1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOcopwd1.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOcopwd1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOcopwd1FocusLost(evt);
            }
        });
        add(txtNGOcopwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 137, -1));

        btnSubmit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, -1, -1));

        lblNGOid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOid.setText("NGO Id :");
        add(lblNGOid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        txtNGOid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOid.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOidFocusLost(evt);
            }
        });
        txtNGOid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNGOidKeyReleased(evt);
            }
        });
        add(txtNGOid, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 134, -1));

        lblNGOid2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        lblNGOname1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        lblNGOPhno1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOPhno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        lblNGOZip1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOZip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        lblNGOAdmin1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        lblNGOpwd2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOpwd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, -1, -1));

        btnCancel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, -1, -1));
        add(LabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 710));
    }// </editor-fold>//GEN-END:initComponents

       public void setBG() {
        try {
            LabelImage.setMinimumSize(new Dimension(1500, 1000));
            LabelImage.setPreferredSize(new Dimension(1500, 1000));
            LabelImage.setMaximumSize(new Dimension(1500, 1000));

            Image img = ImageIO.read(getClass().getResource("/Images/blurbg.jpeg"));

            Image newimg = img.getScaledInstance(2000, 1000, java.awt.Image.SCALE_SMOOTH);
            LabelImage.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    
    private void txtNGOnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOnameFocusLost
        // TODO add your handling code here:
        if(!(txtNGOname.getText().matches("^[a-zA-Z]*$"))){
            lblNGOname1.setText("Invalid input. Please enter only alphabets");
        }
        else{
            lblNGOname1.setText("");
        }
    }//GEN-LAST:event_txtNGOnameFocusLost

    private void txtNGOPhnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOPhnoFocusLost
        // TODO add your handling code here:
        if(!(txtNGOPhno.getText().matches("^[0-9]*$")) || !(txtNGOPhno.getText().length()==10)) {
            lblNGOPhno1.setText("Please enter a valid phone number");
          //  lblNGOPhno1.setForeground(Color.red);
        }
        else{
            lblNGOPhno1.setText("");

        }
    }//GEN-LAST:event_txtNGOPhnoFocusLost

    private void txtNGOZipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOZipFocusLost
        // TODO add your handling code here:
        if((txtNGOZip.getText().matches("^[a-zA-Z]*$"))){
            lblNGOZip1.setText("Invalid input. Please enter only numbers");
            
        }
        else{
            lblNGOZip1.setText("");
        }
    }//GEN-LAST:event_txtNGOZipFocusLost

    private void txtNGOAgentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOAgentFocusLost
        // TODO add your handling code here:
        if(!(txtNGOAgent.getText().matches("^[a-zA-Z]*$"))){
            lblNGOAdmin1.setText("Invalid input. Please enter only alphabets.");
        }
        else{
            lblNGOAdmin1.setText("");
        }
    }//GEN-LAST:event_txtNGOAgentFocusLost

    private void txtNGOcopwd1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOcopwd1FocusLost
        // TODO add your handling code here:
        if(!(txtNGOpwd.getText().equals(txtNGOcopwd1.getText()))){
            lblNGOpwd2.setText("Password Mismatch. Please verify the password entered.");
        }
        else{
            lblNGOpwd2.setText("");
        }
    }//GEN-LAST:event_txtNGOcopwd1FocusLost

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(!nullCheck()){
            UserAccountDirectory uaList = ecosystem.getUserAccountDirectory();
            Employee employee = new Employee();
            employee.setName(txtNGOAgent.getText());
            String role = "NGOAgent";
            NGO ngo = new NGO();
            ngo.setNgoId("ngo"+txtNGOid.getText());
            ngo.setNgoName(txtNGOname.getText());
            ngo.setNgoPhno(txtNGOPhno.getText());
            ngo.setNgoAddress(txtNGOAdd.getText());
            ngo.setNgoCity(txtNGOCity.getText());
            ngo.setNgoState(txtNGOState.getText());
            ngo.setNgoZipcode(txtNGOZip.getText());
            ngo.setNgoAgent(txtNGOAgent.getText());
            UserAccount ngoAccount=new UserAccount();
            ngoAccount.setUsername(txtNGOAgentuname.getText());
            ngoAccount.setPassword(txtNGOpwd.getText());
            // uaList.createUserAccount(txtFCAuname.getText(), txtFCApwd.getText(), employee, new FCAdminRole());
            //                ua = usersList.getUserAccount(txtUserName.getText());
            
            
            ngoAccount.setRole(new NgoRole());
            ngoAccount.setEmployee(employee);
            uad=ecosystem.getUserAccountDirectory();
            uad.createUserAccount(txtNGOAgentuname.getText(), txtNGOpwd.getText(), employee, new NgoRole());
            ecosystem.setUserAccountDirectory(uad);
            ngo.setNgoAccount(ngoAccount);
            ngod = ecosystem.getNgoDir();
            ngod.addNewNGO(ngo);
            ecosystem.setNgoDir(ngod);
            
            JOptionPane.showMessageDialog(this, "NGO added successfully!");
            clearfields();
        }
        else{
            JOptionPane.showMessageDialog(this, "Please make sure that you have filled all mandatory fields");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtNGOidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOidFocusLost
        // TODO add your handling code here:
        if((txtNGOid.getText().matches("^[a-zA-Z]*$"))){
            lblNGOid2.setText("Invalid input. Please enter only numbers");
        }
        else{
            lblNGOid2.setText("");
        }
    }//GEN-LAST:event_txtNGOidFocusLost

    private void txtNGOidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNGOidKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNGOidKeyReleased

    private void txtNGOAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNGOAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNGOAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        clearfields();
    }//GEN-LAST:event_btnCancelActionPerformed

    private boolean nullCheck() {
        if(txtNGOid.getText().length()!=0 && txtNGOname.getText().length()!=0 && 
                txtNGOPhno.getText().length()!=0 && txtNGOAdd.getText().length()!=0 && txtNGOCity.getText().length()!=0 && 
                txtNGOState.getText().length()!=0 && txtNGOZip.getText().length()!=0 && txtNGOAgent.getText().length()!=0 && 
                txtNGOAgentuname.getText().length()!=0 && txtNGOpwd.getText().length()!=0 && txtNGOcopwd1.getText().length()!=0)
            {
                return false;
            }
            else return true;
        }
    
    private void clearfields() {
        txtNGOname.setText("");
        txtNGOPhno.setText("");
        txtNGOAdd.setText("");
        txtNGOCity.setText("");
        txtNGOState.setText("");
        txtNGOZip.setText("");
        txtNGOAgent.setText("");
        txtNGOAgentuname.setText("");
        txtNGOpwd.setText("");
        txtNGOcopwd1.setText("");
        txtNGOid.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImage;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblAddNGOTitle;
    private javax.swing.JLabel lblNGOAdd;
    private javax.swing.JLabel lblNGOAdmin1;
    private javax.swing.JLabel lblNGOAgent;
    private javax.swing.JLabel lblNGOAgentuname;
    private javax.swing.JLabel lblNGOCity;
    private javax.swing.JLabel lblNGOPhno;
    private javax.swing.JLabel lblNGOPhno1;
    private javax.swing.JLabel lblNGOState;
    private javax.swing.JLabel lblNGOZip;
    private javax.swing.JLabel lblNGOZip1;
    private javax.swing.JLabel lblNGOcopwd1;
    private javax.swing.JLabel lblNGOid;
    private javax.swing.JLabel lblNGOid2;
    private javax.swing.JLabel lblNGOname;
    private javax.swing.JLabel lblNGOname1;
    private javax.swing.JLabel lblNGOpwd;
    private javax.swing.JLabel lblNGOpwd2;
    private javax.swing.JTextField txtNGOAdd;
    private javax.swing.JTextField txtNGOAgent;
    private javax.swing.JTextField txtNGOAgentuname;
    private javax.swing.JTextField txtNGOCity;
    private javax.swing.JTextField txtNGOPhno;
    private javax.swing.JTextField txtNGOState;
    private javax.swing.JTextField txtNGOZip;
    private javax.swing.JTextField txtNGOcopwd1;
    private javax.swing.JTextField txtNGOid;
    private javax.swing.JTextField txtNGOname;
    private javax.swing.JTextField txtNGOpwd;
    // End of variables declaration//GEN-END:variables
}
