/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.NGO.NGO;
import Business.NGO.NGODirectory;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aravindasagiraju
 */
public class AddNGOPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddNGOPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    NGODirectory ngod;
    public AddNGOPanel(JPanel userProcessContainer, EcoSystem ecosystem) throws IOException {
        initComponents();

//        imageLbl.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//        imageLbl.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//        imageLbl.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//
//        Image img = ImageIO.read(getClass().getResource("/Images/blurbg.jpeg"));
//
//        Image newimg = img.getScaledInstance(userProcessContainer.getWidth(), userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
//        imageLbl.setIcon(new ImageIcon(newimg));

          this.userProcessContainer = userProcessContainer;
          this.ecosystem = ecosystem;
          if(ecosystem.getNgoDir() == null){
              ecosystem.setNgoDir(new NGODirectory());
          }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddNGOTitle = new javax.swing.JLabel();
        lblNGOname = new javax.swing.JLabel();
        txtNGOname = new javax.swing.JTextField();
        lblNGOPhno = new javax.swing.JLabel();
        txtNGOPhno = new javax.swing.JTextField();
        lblNGOAdd = new javax.swing.JLabel();
        txtNGOAdd = new javax.swing.JTextField();
        lblNGOCity = new javax.swing.JLabel();
        txtNGOCity = new javax.swing.JTextField();
        lblNGOState = new javax.swing.JLabel();
        txtNGOState = new javax.swing.JTextField();
        lblNGOZip = new javax.swing.JLabel();
        txtNGOZip = new javax.swing.JTextField();
        lblNGOAgent = new javax.swing.JLabel();
        txtNGOAgent = new javax.swing.JTextField();
        lblNGOAgentuname = new javax.swing.JLabel();
        txtNGOAgentuname = new javax.swing.JTextField();
        lblNGOpwd = new javax.swing.JLabel();
        txtNGOpwd = new javax.swing.JTextField();
        lblNGOcopwd1 = new javax.swing.JLabel();
        txtNGOcopwd1 = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblNGOid = new javax.swing.JLabel();
        txtNGOid = new javax.swing.JTextField();
        lblNGOid2 = new javax.swing.JLabel();
        lblNGOname1 = new javax.swing.JLabel();
        lblNGOPhno1 = new javax.swing.JLabel();
        lblNGOZip1 = new javax.swing.JLabel();
        lblNGOAdmin1 = new javax.swing.JLabel();
        lblNGOpwd2 = new javax.swing.JLabel();

        lblAddNGOTitle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAddNGOTitle.setText("Add NGO");

        lblNGOname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOname.setText("NGO Name*");

        txtNGOname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOname.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOnameFocusLost(evt);
            }
        });

        lblNGOPhno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOPhno.setText("Phone Number*");

        txtNGOPhno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOPhno.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOPhno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOPhnoFocusLost(evt);
            }
        });

        lblNGOAdd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOAdd.setText("Address*");

        txtNGOAdd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOAdd.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNGOAddActionPerformed(evt);
            }
        });

        lblNGOCity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOCity.setText("City*");

        txtNGOCity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOCity.setPreferredSize(new java.awt.Dimension(150, 25));

        lblNGOState.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOState.setText("State*");

        txtNGOState.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOState.setPreferredSize(new java.awt.Dimension(150, 25));

        lblNGOZip.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOZip.setText("Zipcode*");

        txtNGOZip.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOZip.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOZip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOZipFocusLost(evt);
            }
        });

        lblNGOAgent.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOAgent.setText("NGO Agent*");

        txtNGOAgent.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOAgent.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOAgent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOAgentFocusLost(evt);
            }
        });

        lblNGOAgentuname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOAgentuname.setText("NGO Agent Username*");

        txtNGOAgentuname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOAgentuname.setPreferredSize(new java.awt.Dimension(150, 25));

        lblNGOpwd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOpwd.setText("Password*");

        txtNGOpwd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOpwd.setPreferredSize(new java.awt.Dimension(150, 25));

        lblNGOcopwd1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOcopwd1.setText("Confirm Password*");

        txtNGOcopwd1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOcopwd1.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOcopwd1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOcopwd1FocusLost(evt);
            }
        });

        btnSubmit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblNGOid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOid.setText("NGO Id*");

        txtNGOid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOid.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOidFocusLost(evt);
            }
        });
        txtNGOid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNGOidKeyReleased(evt);
            }
        });

        lblNGOid2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOname1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOPhno1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOZip1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOAdmin1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOpwd2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(lblAddNGOTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNGOPhno)
                            .addComponent(lblNGOAdd)
                            .addComponent(lblNGOCity)
                            .addComponent(lblNGOState)
                            .addComponent(lblNGOZip)
                            .addComponent(lblNGOAgentuname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNGOpwd)
                            .addComponent(lblNGOcopwd1)
                            .addComponent(lblNGOAgent)
                            .addComponent(lblNGOname)
                            .addComponent(lblNGOid))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNGOname, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGOPhno, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGOAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGOCity, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGOState, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGOZip, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGOAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGOAgentuname, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGOpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGOcopwd1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGOid, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnSubmit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNGOname1)
                    .addComponent(lblNGOPhno1)
                    .addComponent(lblNGOZip1)
                    .addComponent(lblNGOAdmin1)
                    .addComponent(lblNGOpwd2)
                    .addComponent(lblNGOid2))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddNGOTitle)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNGOid)
                    .addComponent(txtNGOid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNGOid2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNGOname)
                    .addComponent(txtNGOname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNGOname1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNGOPhno)
                    .addComponent(txtNGOPhno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNGOPhno1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNGOAdd)
                    .addComponent(txtNGOAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNGOCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNGOCity))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNGOState)
                    .addComponent(txtNGOState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNGOZip)
                    .addComponent(txtNGOZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNGOZip1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNGOAgent)
                    .addComponent(txtNGOAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNGOAdmin1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNGOAgentuname)
                    .addComponent(txtNGOAgentuname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNGOpwd)
                    .addComponent(txtNGOpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNGOcopwd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNGOcopwd1)
                    .addComponent(lblNGOpwd2))
                .addGap(27, 27, 27)
                .addComponent(btnSubmit)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNGOnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOnameFocusLost
        // TODO add your handling code here:
        if(!(txtNGOname.getText().matches("^[a-zA-Z]*$"))){
            lblNGOname1.setText("Invalid input. Please enter only alphabets");
        }
        else{
            lblNGOname1.setText("");
        }
    }//GEN-LAST:event_txtNGOnameFocusLost

    private void txtNGOPhnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOPhnoFocusLost
        // TODO add your handling code here:
        if(!(txtNGOPhno.getText().matches("^[0-9]*$")) || !(txtNGOPhno.getText().length()==10)) {
            lblNGOPhno1.setText("Please enter a valid phone number");
        }
        else{
            lblNGOPhno1.setText("");

        }
    }//GEN-LAST:event_txtNGOPhnoFocusLost

    private void txtNGOZipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOZipFocusLost
        // TODO add your handling code here:
        if((txtNGOZip.getText().matches("^[a-zA-Z]*$"))){
            lblNGOZip1.setText("Invalid input. Please enter only numbers");
        }
        else{
            lblNGOZip1.setText("");
        }
    }//GEN-LAST:event_txtNGOZipFocusLost

    private void txtNGOAgentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOAgentFocusLost
        // TODO add your handling code here:
        if(!(txtNGOAgent.getText().matches("^[a-zA-Z]*$"))){
            lblNGOAdmin1.setText("Invalid input. Please enter only alphabets.");
        }
        else{
            lblNGOAdmin1.setText("");
        }
    }//GEN-LAST:event_txtNGOAgentFocusLost

    private void txtNGOcopwd1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOcopwd1FocusLost
        // TODO add your handling code here:
        if(!(txtNGOpwd.getText().equals(txtNGOcopwd1.getText()))){
            lblNGOpwd2.setText("Password Mismatch. Please verify the password entered.");
        }
        else{
            lblNGOpwd2.setText("");
        }
    }//GEN-LAST:event_txtNGOcopwd1FocusLost

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(!nullCheck()){
            UserAccountDirectory uaList = ecosystem.getUserAccountDirectory();
            Employee employee = new Employee();
            employee.setName(txtNGOAgent.getText());
            String role = "NGOAgent";
            NGO ngo = new NGO();
            ngo.setNgoId("ngo"+txtNGOid.getText());
            ngo.setNgoName(txtNGOname.getText());
            ngo.setNgoPhno(txtNGOPhno.getText());
            ngo.setNgoAddress(txtNGOAdd.getText());
            ngo.setNgoCity(txtNGOCity.getText());
            ngo.setNgoState(txtNGOState.getText());
            ngo.setNgoZipcode(txtNGOZip.getText());
            ngo.setNgoAgent(txtNGOAgent.getText());
            UserAccount ngoAccount=new UserAccount();
            ngoAccount.setUsername(txtNGOAgentuname.getText());
            ngoAccount.setPassword(txtNGOpwd.getText());
            // uaList.createUserAccount(txtFCAuname.getText(), txtFCApwd.getText(), employee, new FCAdminRole());
            //                ua = usersList.getUserAccount(txtUserName.getText());
            ngo.setNgoAccount(ngoAccount);
            ngod = ecosystem.getNgoDir();
            ngod.addNewNGO(ngo);
            ecosystem.setNgoDir(ngod);
            JOptionPane.showMessageDialog(this, "NGO added successfully!");
            clearfields();
        }
        else{
            JOptionPane.showMessageDialog(this, "Please make sure that you have filled all mandatory fields");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtNGOidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOidFocusLost
        // TODO add your handling code here:
        if((txtNGOid.getText().matches("^[a-zA-Z]*$"))){
            lblNGOid2.setText("Invalid input. Please enter only numbers");
        }
        else{
            lblNGOid2.setText("");
        }
    }//GEN-LAST:event_txtNGOidFocusLost

    private void txtNGOidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNGOidKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNGOidKeyReleased

    private void txtNGOAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNGOAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNGOAddActionPerformed

    private boolean nullCheck() {
        if(txtNGOid.getText().length()!=0 && txtNGOname.getText().length()!=0 && 
                txtNGOPhno.getText().length()!=0 && txtNGOAdd.getText().length()!=0 && txtNGOCity.getText().length()!=0 && 
                txtNGOState.getText().length()!=0 && txtNGOZip.getText().length()!=0 && txtNGOAgent.getText().length()!=0 && 
                txtNGOAgentuname.getText().length()!=0 && txtNGOpwd.getText().length()!=0 && txtNGOcopwd1.getText().length()!=0)
            {
                return false;
            }
            else return true;
        }
    
    private void clearfields() {
        txtNGOname.setText("");
        txtNGOPhno.setText("");
        txtNGOAdd.setText("");
        txtNGOCity.setText("");
        txtNGOState.setText("");
        txtNGOZip.setText("");
        txtNGOAgent.setText("");
        txtNGOAgentuname.setText("");
        txtNGOpwd.setText("");
        txtNGOcopwd1.setText("");
        txtNGOid.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblAddNGOTitle;
    private javax.swing.JLabel lblNGOAdd;
    private javax.swing.JLabel lblNGOAdmin1;
    private javax.swing.JLabel lblNGOAgent;
    private javax.swing.JLabel lblNGOAgentuname;
    private javax.swing.JLabel lblNGOCity;
    private javax.swing.JLabel lblNGOPhno;
    private javax.swing.JLabel lblNGOPhno1;
    private javax.swing.JLabel lblNGOState;
    private javax.swing.JLabel lblNGOZip;
    private javax.swing.JLabel lblNGOZip1;
    private javax.swing.JLabel lblNGOcopwd1;
    private javax.swing.JLabel lblNGOid;
    private javax.swing.JLabel lblNGOid2;
    private javax.swing.JLabel lblNGOname;
    private javax.swing.JLabel lblNGOname1;
    private javax.swing.JLabel lblNGOpwd;
    private javax.swing.JLabel lblNGOpwd2;
    private javax.swing.JTextField txtNGOAdd;
    private javax.swing.JTextField txtNGOAgent;
    private javax.swing.JTextField txtNGOAgentuname;
    private javax.swing.JTextField txtNGOCity;
    private javax.swing.JTextField txtNGOPhno;
    private javax.swing.JTextField txtNGOState;
    private javax.swing.JTextField txtNGOZip;
    private javax.swing.JTextField txtNGOcopwd1;
    private javax.swing.JTextField txtNGOid;
    private javax.swing.JTextField txtNGOname;
    private javax.swing.JTextField txtNGOpwd;
    // End of variables declaration//GEN-END:variables
}
