/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author aravindasagiraju
 */
public class ManageNGOJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageNGOJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;

    public ManageNGOJPanel(JPanel userProcessContainer, EcoSystem ecosystem) throws IOException {
        initComponents();
        this.ecosystem = ecosystem;
        this.userProcessContainer = userProcessContainer;
        lblbgc.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
        lblbgc.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
        lblbgc.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

        Image img = ImageIO.read(getClass().getResource("/Images/blurbg.jpeg"));

        Image newimg = img.getScaledInstance(userProcessContainer.getWidth(), userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
        lblbgc.setIcon(new ImageIcon(newimg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPaneNGO = new javax.swing.JSplitPane();
        NGOControlPanel = new javax.swing.JPanel();
        btnAddNGO = new javax.swing.JButton();
        btnViewNGO = new javax.swing.JButton();
        SysAdminWorkareaPanel = new javax.swing.JPanel();
        lblbgc = new javax.swing.JLabel();

        NGOControlPanel.setPreferredSize(new java.awt.Dimension(150, 600));

        btnAddNGO.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddNGO.setText("Add NGO");
        btnAddNGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNGOActionPerformed(evt);
            }
        });

        btnViewNGO.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnViewNGO.setText("View/Modify");
        btnViewNGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewNGOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NGOControlPanelLayout = new javax.swing.GroupLayout(NGOControlPanel);
        NGOControlPanel.setLayout(NGOControlPanelLayout);
        NGOControlPanelLayout.setHorizontalGroup(
            NGOControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NGOControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NGOControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnViewNGO, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(btnAddNGO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        NGOControlPanelLayout.setVerticalGroup(
            NGOControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NGOControlPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnAddNGO)
                .addGap(26, 26, 26)
                .addComponent(btnViewNGO)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        SplitPaneNGO.setLeftComponent(NGOControlPanel);

        SysAdminWorkareaPanel.setPreferredSize(new java.awt.Dimension(840, 600));

        javax.swing.GroupLayout SysAdminWorkareaPanelLayout = new javax.swing.GroupLayout(SysAdminWorkareaPanel);
        SysAdminWorkareaPanel.setLayout(SysAdminWorkareaPanelLayout);
        SysAdminWorkareaPanelLayout.setHorizontalGroup(
            SysAdminWorkareaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblbgc, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );
        SysAdminWorkareaPanelLayout.setVerticalGroup(
            SysAdminWorkareaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblbgc, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        SplitPaneNGO.setRightComponent(SysAdminWorkareaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneNGO, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneNGO)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNGOActionPerformed
        try {
            // TODO add your handling code here:
            AddNGOPanel objAddNGO = new AddNGOPanel(userProcessContainer,ecosystem);
            SplitPaneNGO.setRightComponent(objAddNGO);
        } catch (IOException ex) {
            Logger.getLogger(ManageNGOJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddNGOActionPerformed

    private void btnViewNGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewNGOActionPerformed
        try {
            // TODO add your handling code here:
            ViewModifyNGOPanel objViewModNGO = new ViewModifyNGOPanel(userProcessContainer,ecosystem);
            SplitPaneNGO.setRightComponent(objViewModNGO);
        } catch (IOException ex) {
            Logger.getLogger(ManageNGOJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewNGOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NGOControlPanel;
    private javax.swing.JSplitPane SplitPaneNGO;
    private javax.swing.JPanel SysAdminWorkareaPanel;
    private javax.swing.JButton btnAddNGO;
    private javax.swing.JButton btnViewNGO;
    private javax.swing.JLabel lblbgc;
    // End of variables declaration//GEN-END:variables
}
