/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.FCWarehouse.FCWarehouse;
import Business.NGO.NGO;
import Business.NGO.NGODirectory;
import Business.UserAccount.UserAccount;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aravindasagiraju
 */
public class ViewModifyNGOPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewModifyNGOPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    NGODirectory ngod;
    public ViewModifyNGOPanel(JPanel userProcessContainer, EcoSystem ecosystem) throws IOException {
        initComponents();
        
//        imageLbl.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//        imageLbl.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//        imageLbl.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//
//        Image img = ImageIO.read(getClass().getResource("/Images/blurbg.jpeg"));
//
//        Image newimg = img.getScaledInstance(userProcessContainer.getWidth(), userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
//        imageLbl.setIcon(new ImageIcon(newimg));
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        if(ecosystem.getNgoDir() == null){
              ecosystem.setNgoDir(new NGODirectory());
          }
        populatengotable();
        txtNGOuname.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddNGOTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNGO = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lblNGOname = new javax.swing.JLabel();
        txtNGOname = new javax.swing.JTextField();
        lblNGOPhno = new javax.swing.JLabel();
        txtNGOPhno = new javax.swing.JTextField();
        lblNGOAdd = new javax.swing.JLabel();
        txtNGOAdd = new javax.swing.JTextField();
        lblNGOCity = new javax.swing.JLabel();
        txtNGOCity = new javax.swing.JTextField();
        lblNGOState = new javax.swing.JLabel();
        txtNGOState = new javax.swing.JTextField();
        lblNGOZip = new javax.swing.JLabel();
        txtNGOZip = new javax.swing.JTextField();
        lblNGOAgent = new javax.swing.JLabel();
        txtNGOAgent = new javax.swing.JTextField();
        lblNGOuname = new javax.swing.JLabel();
        txtNGOuname = new javax.swing.JTextField();
        lblNGOpwd = new javax.swing.JLabel();
        txtNGOpwd = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        lblNGOname1 = new javax.swing.JLabel();
        lblNGOPhno1 = new javax.swing.JLabel();
        lblNGOAdd1 = new javax.swing.JLabel();
        lbNGOCity1 = new javax.swing.JLabel();
        lblNGOState1 = new javax.swing.JLabel();
        lblNGOZip1 = new javax.swing.JLabel();
        lblNGOAgent1 = new javax.swing.JLabel();
        lblNGOuname1 = new javax.swing.JLabel();
        lblNGOpwd1 = new javax.swing.JLabel();
        lblNGOid = new javax.swing.JLabel();
        lblNGOid1 = new javax.swing.JLabel();

        lblAddNGOTitle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAddNGOTitle.setText("View/Modify NGO");

        tblNGO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NGO ID", "Name", "NGO Agent", "Phone Number", "Address", "City", "State", "Zipcode"
            }
        ));
        jScrollPane1.setViewportView(tblNGO);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lblNGOname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOname.setText("NGO Name");

        txtNGOname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOname.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOnameFocusLost(evt);
            }
        });
        txtNGOname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNGOnameKeyReleased(evt);
            }
        });

        lblNGOPhno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOPhno.setText("Phone Number");

        txtNGOPhno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOPhno.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOPhno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOPhnoFocusLost(evt);
            }
        });
        txtNGOPhno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNGOPhnoKeyReleased(evt);
            }
        });

        lblNGOAdd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOAdd.setText("Address");

        txtNGOAdd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOAdd.setPreferredSize(new java.awt.Dimension(150, 25));

        lblNGOCity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOCity.setText("City");

        txtNGOCity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOCity.setPreferredSize(new java.awt.Dimension(150, 25));

        lblNGOState.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOState.setText("State");

        txtNGOState.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOState.setPreferredSize(new java.awt.Dimension(150, 25));

        lblNGOZip.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOZip.setText("Zipcode");

        txtNGOZip.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOZip.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOZip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOZipFocusLost(evt);
            }
        });

        lblNGOAgent.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOAgent.setText("NGO Agent");

        txtNGOAgent.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOAgent.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOAgent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOAgentFocusLost(evt);
            }
        });

        lblNGOuname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOuname.setText("NGO Agent Username");

        txtNGOuname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOuname.setPreferredSize(new java.awt.Dimension(150, 25));

        lblNGOpwd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOpwd.setText("Password");

        txtNGOpwd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOpwd.setPreferredSize(new java.awt.Dimension(150, 25));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblNGOname1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOPhno1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOAdd1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lbNGOCity1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOState1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOZip1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOAgent1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOuname1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOpwd1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOid.setText("NGO Id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNGOPhno)
                            .addComponent(lblNGOAdd)
                            .addComponent(lblNGOCity)
                            .addComponent(lblNGOState)
                            .addComponent(lblNGOZip)
                            .addComponent(lblNGOAgent)
                            .addComponent(lblNGOuname)
                            .addComponent(lblNGOpwd)
                            .addComponent(lblNGOname))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNGOCity, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGOState, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGOZip, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGOAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGOuname, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGOpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGOPhno, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGOAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGOname, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNGOZip1)
                    .addComponent(lblNGOAdd1)
                    .addComponent(lbNGOCity1)
                    .addComponent(lblNGOState1)
                    .addComponent(lblNGOAgent1)
                    .addComponent(lblNGOuname1)
                    .addComponent(lblNGOpwd1)
                    .addComponent(lblNGOname1)
                    .addComponent(lblNGOPhno1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblNGOid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNGOid1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(lblAddNGOTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNGOname1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNGOPhno1)
                .addGap(36, 36, 36)
                .addComponent(lblNGOAdd1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNGOCity1)
                .addGap(18, 18, 18)
                .addComponent(lblNGOState1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNGOZip1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNGOAgent1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNGOuname1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNGOpwd1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddNGOTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNGOid)
                        .addComponent(lblNGOid1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelete)
                        .addComponent(btnEdit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNGOname)
                    .addComponent(txtNGOname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNGOPhno)
                    .addComponent(txtNGOPhno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNGOAdd)
                    .addComponent(txtNGOAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNGOCity)
                    .addComponent(txtNGOCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNGOState)
                    .addComponent(txtNGOState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNGOZip)
                    .addComponent(txtNGOZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNGOAgent)
                    .addComponent(txtNGOAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNGOuname)
                    .addComponent(txtNGOuname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNGOpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNGOpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(108, 108, 108))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblNGO.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a record to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblNGO.getModel();
        NGO selectedNGO = (NGO)model.getValueAt(selectedRowIndex, 0);
        /* // First delete the customer from employee
        this.system.getEmployeeDirectory().deleteEmployee(selectedRest.getResManagerName());
        // And thne delete the userAccount
        this.system.getUserAccountDirectory().deleteUserAcc(
            this.system.getRestaurantDirectory().getResList().
            get(selectedRowIndex).getUserAcc()
        );
        // finally delete the user from customer directory*/
        ngod= ecosystem.getNgoDir();
        ngod.deleteNGO(selectedNGO);
        ecosystem.setNgoDir(ngod);
        JOptionPane.showMessageDialog(this, "NGO deleted Successfully");
        populatengotable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblNGO.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a record to Edit");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblNGO.getModel();
        NGO selectedNGO = (NGO)model.getValueAt(selectedRowIndex, 0);
        lblNGOid1.setText(selectedNGO.getNgoId());
        txtNGOname.setText(selectedNGO.getNgoName());
        txtNGOPhno.setText(selectedNGO.getNgoPhno());
        txtNGOAdd.setText(selectedNGO.getNgoAddress());
        txtNGOCity.setText(selectedNGO.getNgoCity());
        txtNGOState.setText(selectedNGO.getNgoState());
        txtNGOZip.setText(selectedNGO.getNgoZipcode());
        txtNGOAgent.setText(selectedNGO.getNgoAgent());
        txtNGOuname.setText(selectedNGO.getNgoAccount().getUsername());
        txtNGOpwd.setText(selectedNGO.getNgoAccount().getPassword());
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtNGOnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOnameFocusLost
        // TODO add your handling code here:
        if(!(txtNGOname.getText().matches("^[a-zA-Z]*$"))){
            lblNGOname1.setText("Invalid input. Please enter only alphabets");
        }
        else{
            lblNGOname1.setText("");
        }
    }//GEN-LAST:event_txtNGOnameFocusLost

    private void txtNGOnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNGOnameKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNGOnameKeyReleased

    private void txtNGOPhnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOPhnoFocusLost
        // TODO add your handling code here:
        if(!(txtNGOPhno.getText().matches("^[0-9]*$")) || !(txtNGOPhno.getText().length()==10)) {
            lblNGOPhno1.setText("Please enter a valid phone number");
        }
        else{
            lblNGOPhno1.setText("");

        }
    }//GEN-LAST:event_txtNGOPhnoFocusLost

    private void txtNGOPhnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNGOPhnoKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNGOPhnoKeyReleased

    private void txtNGOZipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOZipFocusLost
        // TODO add your handling code here:
        if((txtNGOZip.getText().matches("^[a-zA-Z]*$"))){
            lblNGOZip1.setText("Invalid input. Please enter only numbers");
        }
        else{
            lblNGOZip1.setText("");
        }
    }//GEN-LAST:event_txtNGOZipFocusLost

    private void txtNGOAgentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOAgentFocusLost
        // TODO add your handling code here:
        if(!(txtNGOAgent.getText().matches("^[a-zA-Z]*$"))){
            lblNGOAgent1.setText("Invalid input. Please enter only alphabets");
        }
        else{
            lblNGOAgent1.setText("");
        }
    }//GEN-LAST:event_txtNGOAgentFocusLost

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblNGO.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a record to update");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblNGO.getModel();
        String NGOid = lblNGOid1.getText();

        ArrayList<NGO> ngoList = ecosystem.getNgoDir().getNgoList();
        for(NGO f: ngoList)
        {
            if(f.getNgoId().equals(NGOid))
            {
                f.setNgoName(txtNGOname.getText());
                f.setNgoPhno(txtNGOPhno.getText());
                f.setNgoAddress(txtNGOAdd.getText());
                f.setNgoCity(txtNGOCity.getText());
                f.setNgoState(txtNGOState.getText());
                f.setNgoZipcode(txtNGOZip.getText());
                f.setNgoAgent(txtNGOAgent.getText());
                UserAccount NGOua=new UserAccount();
                NGOua.setUsername(txtNGOuname.getText());
                NGOua.setPassword(txtNGOpwd.getText());
                f.setNgoAccount(NGOua);
                break;
            }

        }
        // ecosystem.setFCWDirectory(fcwList);
        ngod = ecosystem.getNgoDir();
        ecosystem.setNgoDir(ngod);
        JOptionPane.showMessageDialog(this, "NGO details updated successfully");
        clearfields();
        populatengotable();
    }//GEN-LAST:event_btnUpdateActionPerformed
 
    private void populatengotable() {
        DefaultTableModel model = (DefaultTableModel) tblNGO.getModel();
        model.setRowCount(0);
        for(NGO ngo: ecosystem.getNgoDir().getNgoList()){
           Object[] row = new Object[8];
           row[0] =ngo;
           row[1] =ngo.getNgoName();
           row[2] =ngo.getNgoAgent();
           row[3] =ngo.getNgoPhno();
           row[4] =ngo.getNgoAddress();
           row[5] =ngo.getNgoCity();
           row[6] =ngo.getNgoState();
           row[7] =ngo.getNgoZipcode();
           model.addRow(row);
        } 
    }
    
    private void clearfields() {
        txtNGOname.setText("");
        txtNGOPhno.setText("");
        txtNGOAdd.setText("");
        txtNGOCity.setText("");
        txtNGOState.setText("");
        txtNGOZip.setText("");
        txtNGOAgent.setText("");
        txtNGOuname.setText("");
        txtNGOpwd.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNGOCity1;
    private javax.swing.JLabel lblAddNGOTitle;
    private javax.swing.JLabel lblNGOAdd;
    private javax.swing.JLabel lblNGOAdd1;
    private javax.swing.JLabel lblNGOAgent;
    private javax.swing.JLabel lblNGOAgent1;
    private javax.swing.JLabel lblNGOCity;
    private javax.swing.JLabel lblNGOPhno;
    private javax.swing.JLabel lblNGOPhno1;
    private javax.swing.JLabel lblNGOState;
    private javax.swing.JLabel lblNGOState1;
    private javax.swing.JLabel lblNGOZip;
    private javax.swing.JLabel lblNGOZip1;
    private javax.swing.JLabel lblNGOid;
    private javax.swing.JLabel lblNGOid1;
    private javax.swing.JLabel lblNGOname;
    private javax.swing.JLabel lblNGOname1;
    private javax.swing.JLabel lblNGOpwd;
    private javax.swing.JLabel lblNGOpwd1;
    private javax.swing.JLabel lblNGOuname;
    private javax.swing.JLabel lblNGOuname1;
    private javax.swing.JTable tblNGO;
    private javax.swing.JTextField txtNGOAdd;
    private javax.swing.JTextField txtNGOAgent;
    private javax.swing.JTextField txtNGOCity;
    private javax.swing.JTextField txtNGOPhno;
    private javax.swing.JTextField txtNGOState;
    private javax.swing.JTextField txtNGOZip;
    private javax.swing.JTextField txtNGOname;
    private javax.swing.JTextField txtNGOpwd;
    private javax.swing.JTextField txtNGOuname;
    // End of variables declaration//GEN-END:variables
}
