/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.FCWarehouse.FCWarehouse;
import Business.NGO.NGO;
import Business.NGO.NGODirectory;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import userinterface.DonorRole.DonorProfilePanel;

/**
 *
 * @author aravindasagiraju
 */
public class ViewModifyNGOPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewModifyNGOPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    NGODirectory ngod;
    public ViewModifyNGOPanel(JPanel userProcessContainer, EcoSystem ecosystem) throws IOException {
        initComponents();
        
//        imageLbl.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//        imageLbl.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//        imageLbl.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//
//        Image img = ImageIO.read(getClass().getResource("/Images/blurbg.jpeg"));
//
//        Image newimg = img.getScaledInstance(userProcessContainer.getWidth(), userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
//        imageLbl.setIcon(new ImageIcon(newimg));
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        if(ecosystem.getNgoDir() == null){
              ecosystem.setNgoDir(new NGODirectory());
          }
        populatengotable();
        txtNGOuname.setEnabled(false);
        setBG();
        makeTableTransparent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddNGOTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNGO = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblNGOname = new javax.swing.JLabel();
        txtNGOname = new javax.swing.JTextField();
        lblNGOPhno = new javax.swing.JLabel();
        txtNGOPhno = new javax.swing.JTextField();
        lblNGOAdd = new javax.swing.JLabel();
        txtNGOAdd = new javax.swing.JTextField();
        lblNGOCity = new javax.swing.JLabel();
        txtNGOCity = new javax.swing.JTextField();
        lblNGOState = new javax.swing.JLabel();
        txtNGOState = new javax.swing.JTextField();
        lblNGOZip = new javax.swing.JLabel();
        txtNGOZip = new javax.swing.JTextField();
        lblNGOAgent = new javax.swing.JLabel();
        txtNGOAgent = new javax.swing.JTextField();
        lblNGOuname = new javax.swing.JLabel();
        txtNGOuname = new javax.swing.JTextField();
        lblNGOpwd = new javax.swing.JLabel();
        txtNGOpwd = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        lblNGOname1 = new javax.swing.JLabel();
        lblNGOPhno1 = new javax.swing.JLabel();
        lblNGOAdd1 = new javax.swing.JLabel();
        lbNGOCity1 = new javax.swing.JLabel();
        lblNGOState1 = new javax.swing.JLabel();
        lblNGOZip1 = new javax.swing.JLabel();
        lblNGOAgent1 = new javax.swing.JLabel();
        lblNGOuname1 = new javax.swing.JLabel();
        lblNGOpwd1 = new javax.swing.JLabel();
        lblNGOid = new javax.swing.JLabel();
        lblNGOid1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        LabelImg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddNGOTitle.setFont(new java.awt.Font("Georgia", 1, 29)); // NOI18N
        lblAddNGOTitle.setForeground(new java.awt.Color(51, 153, 255));
        lblAddNGOTitle.setText("NGO Details");
        add(lblAddNGOTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 190, 40));

        tblNGO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NGO ID", "Name", "NGO Agent", "Phone Number", "Address", "City", "State", "Zipcode"
            }
        ));
        tblNGO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblNGOMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblNGO);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 820, 130));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 92, -1));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 92, -1));

        jPanel1.setOpaque(false);

        lblNGOname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOname.setText("NGO Name :");

        txtNGOname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOname.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOnameFocusLost(evt);
            }
        });
        txtNGOname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNGOnameKeyReleased(evt);
            }
        });

        lblNGOPhno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOPhno.setText("Phone Number :");

        txtNGOPhno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOPhno.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOPhno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOPhnoFocusLost(evt);
            }
        });
        txtNGOPhno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNGOPhnoKeyReleased(evt);
            }
        });

        lblNGOAdd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOAdd.setText("Address :");

        txtNGOAdd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOAdd.setPreferredSize(new java.awt.Dimension(150, 25));

        lblNGOCity.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOCity.setText("City :");

        txtNGOCity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOCity.setPreferredSize(new java.awt.Dimension(150, 25));

        lblNGOState.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOState.setText("State :");

        txtNGOState.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOState.setPreferredSize(new java.awt.Dimension(150, 25));

        lblNGOZip.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOZip.setText("Zipcode :");

        txtNGOZip.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOZip.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOZip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOZipFocusLost(evt);
            }
        });

        lblNGOAgent.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOAgent.setText("NGO Agent :");

        txtNGOAgent.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOAgent.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOAgent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOAgentFocusLost(evt);
            }
        });

        lblNGOuname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOuname.setText("NGO Agent Username :");

        txtNGOuname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOuname.setPreferredSize(new java.awt.Dimension(150, 25));

        lblNGOpwd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOpwd.setText("Password :");

        txtNGOpwd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOpwd.setPreferredSize(new java.awt.Dimension(150, 25));

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblNGOname1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOPhno1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOAdd1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lbNGOCity1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOState1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOZip1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOAgent1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOuname1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOpwd1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNGOid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNGOid.setText("NGO Id:");

        btnCancel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(lblNGOid1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblNGOPhno)
                        .addGap(19, 19, 19)
                        .addComponent(txtNGOPhno, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(lblNGOZip1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(txtNGOpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(lblNGOPhno1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lblNGOZip))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(lblNGOpwd1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lblNGOpwd))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(lblNGOname1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(txtNGOuname, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lblNGOid))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(lblNGOAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lblNGOAdd))
                    .addComponent(lblNGOuname)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(txtNGOCity, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(txtNGOAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblNGOCity))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(lbNGOCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(txtNGOname, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(lblNGOAgent1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(txtNGOZip, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblNGOname))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(txtNGOAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(txtNGOState, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblNGOState))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblNGOAgent))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(lblNGOState1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(lblNGOuname1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblNGOPhno1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(lblNGOpwd1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblNGOname1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblNGOAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lbNGOCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(lblNGOAgent1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(lblNGOState1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(lblNGOuname1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNGOid1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNGOPhno)
                                    .addComponent(txtNGOPhno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(135, 135, 135)
                                .addComponent(lblNGOZip1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(txtNGOpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(lblNGOZip))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(350, 350, 350)
                                .addComponent(lblNGOpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(310, 310, 310)
                                .addComponent(txtNGOuname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNGOid)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(lblNGOAdd))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(310, 310, 310)
                                .addComponent(lblNGOuname))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(txtNGOCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(txtNGOAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(lblNGOCity))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtNGOname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(txtNGOZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblNGOname))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(txtNGOAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(txtNGOState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(lblNGOState))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(lblNGOAgent)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnCancel))))
                .addGap(23, 23, 23))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 660, -1));
        add(LabelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1490, 770));
    }// </editor-fold>//GEN-END:initComponents

     public void setBG() {
        try {
            LabelImg.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/blurbg.jpeg"));

            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImg.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
      public void makeTableTransparent() {
        tblNGO.setOpaque(false);
        ((DefaultTableCellRenderer) tblNGO.getDefaultRenderer(Object.class)).setOpaque(false);
        tblNGO.setShowGrid(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.WHITE);

        for (int i = 0; i < tblNGO.getModel().getColumnCount(); i++) {
            tblNGO.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }
     
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblNGO.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a record to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblNGO.getModel();
        NGO selectedNGO = (NGO)model.getValueAt(selectedRowIndex, 0);
        /* // First delete the customer from employee
        this.system.getEmployeeDirectory().deleteEmployee(selectedRest.getResManagerName());
        // And thne delete the userAccount
        this.system.getUserAccountDirectory().deleteUserAcc(
            this.system.getRestaurantDirectory().getResList().
            get(selectedRowIndex).getUserAcc()
        );
        // finally delete the user from customer directory*/
        ngod= ecosystem.getNgoDir();
        ngod.deleteNGO(selectedNGO);
        ecosystem.setNgoDir(ngod);
        JOptionPane.showMessageDialog(this, "NGO deleted Successfully");
        populatengotable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblNGO.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a record to Edit");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblNGO.getModel();
        NGO selectedNGO = (NGO)model.getValueAt(selectedRowIndex, 0);
        lblNGOid1.setText(selectedNGO.getNgoId());
        txtNGOname.setText(selectedNGO.getNgoName());
        txtNGOPhno.setText(selectedNGO.getNgoPhno());
        txtNGOAdd.setText(selectedNGO.getNgoAddress());
        txtNGOCity.setText(selectedNGO.getNgoCity());
        txtNGOState.setText(selectedNGO.getNgoState());
        txtNGOZip.setText(selectedNGO.getNgoZipcode());
        txtNGOAgent.setText(selectedNGO.getNgoAgent());
        txtNGOuname.setText(selectedNGO.getNgoAccount().getUsername());
        txtNGOpwd.setText(selectedNGO.getNgoAccount().getPassword());
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtNGOnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOnameFocusLost
        // TODO add your handling code here:
        if(!(txtNGOname.getText().matches("^[a-zA-Z]*$"))){
            lblNGOname1.setText("Invalid input. Please enter only alphabets");
        }
        else{
            lblNGOname1.setText("");
        }
    }//GEN-LAST:event_txtNGOnameFocusLost

    private void txtNGOnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNGOnameKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNGOnameKeyReleased

    private void txtNGOPhnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOPhnoFocusLost
        // TODO add your handling code here:
        if(!(txtNGOPhno.getText().matches("^[0-9]*$")) || !(txtNGOPhno.getText().length()==10)) {
            lblNGOPhno1.setText("Please enter a valid phone number");
        }
        else{
            lblNGOPhno1.setText("");

        }
    }//GEN-LAST:event_txtNGOPhnoFocusLost

    private void txtNGOPhnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNGOPhnoKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNGOPhnoKeyReleased

    private void txtNGOZipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOZipFocusLost
        // TODO add your handling code here:
        if((txtNGOZip.getText().matches("^[a-zA-Z]*$"))){
            lblNGOZip1.setText("Invalid input. Please enter only numbers");
        }
        else{
            lblNGOZip1.setText("");
        }
    }//GEN-LAST:event_txtNGOZipFocusLost

    private void txtNGOAgentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOAgentFocusLost
        // TODO add your handling code here:
        if(!(txtNGOAgent.getText().matches("^[a-zA-Z]*$"))){
            lblNGOAgent1.setText("Invalid input. Please enter only alphabets");
        }
        else{
            lblNGOAgent1.setText("");
        }
    }//GEN-LAST:event_txtNGOAgentFocusLost

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblNGO.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a record to update");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblNGO.getModel();
        String NGOid = lblNGOid1.getText();

        ArrayList<NGO> ngoList = ecosystem.getNgoDir().getNgoList();
        for(NGO f: ngoList)
        {
            if(f.getNgoId().equals(NGOid))
            {
                f.setNgoName(txtNGOname.getText());
                f.setNgoPhno(txtNGOPhno.getText());
                f.setNgoAddress(txtNGOAdd.getText());
                f.setNgoCity(txtNGOCity.getText());
                f.setNgoState(txtNGOState.getText());
                f.setNgoZipcode(txtNGOZip.getText());
                f.setNgoAgent(txtNGOAgent.getText());
                UserAccount NGOua=new UserAccount();
                NGOua.setUsername(txtNGOuname.getText());
                NGOua.setPassword(txtNGOpwd.getText());
                f.setNgoAccount(NGOua);
                break;
            }

        }
        // ecosystem.setFCWDirectory(fcwList);
        ngod = ecosystem.getNgoDir();
        ecosystem.setNgoDir(ngod);
        JOptionPane.showMessageDialog(this, "NGO details updated successfully");
        clearfields();
        populatengotable();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblNGOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNGOMousePressed
        // TODO add your handling code here:
         tblNGO.setSelectionForeground(Color.BLUE);
    }//GEN-LAST:event_tblNGOMousePressed
 
    private void populatengotable() {
        DefaultTableModel model = (DefaultTableModel) tblNGO.getModel();
        model.setRowCount(0);
        for(NGO ngo: ecosystem.getNgoDir().getNgoList()){
           Object[] row = new Object[8];
           row[0] =ngo;
           row[1] =ngo.getNgoName();
           row[2] =ngo.getNgoAgent();
           row[3] =ngo.getNgoPhno();
           row[4] =ngo.getNgoAddress();
           row[5] =ngo.getNgoCity();
           row[6] =ngo.getNgoState();
           row[7] =ngo.getNgoZipcode();
           model.addRow(row);
        } 
    }
    
    private void clearfields() {
        txtNGOname.setText("");
        txtNGOPhno.setText("");
        txtNGOAdd.setText("");
        txtNGOCity.setText("");
        txtNGOState.setText("");
        txtNGOZip.setText("");
        txtNGOAgent.setText("");
        txtNGOuname.setText("");
        txtNGOpwd.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImg;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNGOCity1;
    private javax.swing.JLabel lblAddNGOTitle;
    private javax.swing.JLabel lblNGOAdd;
    private javax.swing.JLabel lblNGOAdd1;
    private javax.swing.JLabel lblNGOAgent;
    private javax.swing.JLabel lblNGOAgent1;
    private javax.swing.JLabel lblNGOCity;
    private javax.swing.JLabel lblNGOPhno;
    private javax.swing.JLabel lblNGOPhno1;
    private javax.swing.JLabel lblNGOState;
    private javax.swing.JLabel lblNGOState1;
    private javax.swing.JLabel lblNGOZip;
    private javax.swing.JLabel lblNGOZip1;
    private javax.swing.JLabel lblNGOid;
    private javax.swing.JLabel lblNGOid1;
    private javax.swing.JLabel lblNGOname;
    private javax.swing.JLabel lblNGOname1;
    private javax.swing.JLabel lblNGOpwd;
    private javax.swing.JLabel lblNGOpwd1;
    private javax.swing.JLabel lblNGOuname;
    private javax.swing.JLabel lblNGOuname1;
    private javax.swing.JTable tblNGO;
    private javax.swing.JTextField txtNGOAdd;
    private javax.swing.JTextField txtNGOAgent;
    private javax.swing.JTextField txtNGOCity;
    private javax.swing.JTextField txtNGOPhno;
    private javax.swing.JTextField txtNGOState;
    private javax.swing.JTextField txtNGOZip;
    private javax.swing.JTextField txtNGOname;
    private javax.swing.JTextField txtNGOpwd;
    private javax.swing.JTextField txtNGOuname;
    // End of variables declaration//GEN-END:variables
}
