/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.DonorRole;

import Business.Donation.Donation;
import Business.Donation.DonationDirectory;
import Business.Donor.Donor;
import Business.EcoSystem;
import Business.FCWarehouse.FCWarehouse;
import Business.UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sowmyachinimilli
 */
public class DonateNowPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonateNowPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAcc;
    String donUName;
    String donName;
    String donState;
    DonationDirectory donatD;
    public DonateNowPanel(JPanel userProcessContainer,EcoSystem ecosystem,UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem =ecosystem;
        this.userAcc = userAcc;
        donUName = userAcc.getUsername();
        donName  = userAcc.getEmployee().getName();
        if(ecosystem.getDonatDirectory()== null){
         ecosystem.setDonatDirectory(new DonationDirectory());
        }
        String donState = ecosystem.getDonDir().getdonState(donUName);
        ArrayList<String> CityList = new ArrayList<String>();
        for (FCWarehouse fcw : ecosystem.getFCWDirectory().getFcwList()){
            if(fcw.getFcwState().equals(donState)){
                CityList.add(fcw.getFcwCity());
            }
        }         
        cbCity.setModel(new DefaultComboBoxModel<String>(CityList.toArray(new String[0])));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDonProfileTitle = new javax.swing.JLabel();
        lblDfditem = new javax.swing.JLabel();
        lblDfdquan = new javax.swing.JLabel();
        txtDfditem = new javax.swing.JTextField();
        sdQuan = new javax.swing.JSlider();
        lblDonProfileTitle1 = new javax.swing.JLabel();
        chkAdd = new javax.swing.JCheckBox();
        lblDadd = new javax.swing.JLabel();
        txtDadd = new javax.swing.JTextField();
        lblDcity = new javax.swing.JLabel();
        txtDcity = new javax.swing.JTextField();
        lblDstate = new javax.swing.JLabel();
        txtDstate = new javax.swing.JTextField();
        lblDzip = new javax.swing.JLabel();
        txtDzip = new javax.swing.JTextField();
        lblDfdquan2 = new javax.swing.JLabel();
        cbCity = new javax.swing.JComboBox<>();
        lblDfdquan3 = new javax.swing.JLabel();
        cbWH = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        lblDfdquan1 = new javax.swing.JLabel();
        lblDfdquan4 = new javax.swing.JLabel();
        lblDfdquan5 = new javax.swing.JLabel();

        lblDonProfileTitle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDonProfileTitle.setText("Donate Food Details");

        lblDfditem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDfditem.setText("Food Item");

        lblDfdquan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDfdquan.setText("Quantity");

        txtDfditem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDfditem.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDfditem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDfditemFocusLost(evt);
            }
        });

        sdQuan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        sdQuan.setMajorTickSpacing(10);
        sdQuan.setMinimum(10);
        sdQuan.setPaintTicks(true);
        sdQuan.setAutoscrolls(true);

        lblDonProfileTitle1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDonProfileTitle1.setText("Pickup Address");

        chkAdd.setText("Same Address as in Profile");
        chkAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAddActionPerformed(evt);
            }
        });

        lblDadd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDadd.setText("Address");

        txtDadd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDadd.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDadd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDaddFocusLost(evt);
            }
        });

        lblDcity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDcity.setText("City");

        txtDcity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDcity.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDcity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDcityFocusLost(evt);
            }
        });

        lblDstate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDstate.setText("State");

        txtDstate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDstate.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDstate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDstateFocusLost(evt);
            }
        });

        lblDzip.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDzip.setText("Zipcode");

        txtDzip.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDzip.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDzip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDzipFocusLost(evt);
            }
        });

        lblDfdquan2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDfdquan2.setText("Select city");

        cbCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCityActionPerformed(evt);
            }
        });

        lblDfdquan3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDfdquan3.setText("Select a nearest warehouse");

        cbWH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSubmit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSubmit.setText("Submit Request");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblDfdquan1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDfdquan1.setText("Min 10");

        lblDfdquan4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDfdquan4.setText("Max 100");

        lblDfdquan5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDfdquan5.setText("persons");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(lblDonProfileTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblDonProfileTitle1)
                                .addGap(39, 39, 39))
                            .addComponent(chkAdd, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblDzip))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(214, 214, 214)
                                            .addComponent(lblDfditem))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(lblDfdquan2)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(lblDfdquan3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(lblDfdquan)))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDcity))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblDadd))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cbWH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDstate))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblDfdquan4)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtDfditem, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(sdQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDfdquan5)
                                        .addGap(0, 182, Short.MAX_VALUE)))))
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(lblDfdquan1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDzip, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDcity, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDadd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDstate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(428, 428, 428)
                .addComponent(btnSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblDonProfileTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblDonProfileTitle1)
                        .addGap(18, 18, 18)
                        .addComponent(chkAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDfditem)
                                    .addComponent(txtDfditem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sdQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(lblDfdquan))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(lblDfdquan5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDadd)
                                    .addComponent(txtDadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDcity)
                                    .addComponent(txtDcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDfdquan1)
                                    .addComponent(lblDfdquan4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDfdquan2))
                                .addGap(7, 7, 7)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDstate)
                    .addComponent(txtDstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDfdquan3)
                    .addComponent(cbWH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDzip)
                    .addComponent(txtDzip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(123, 123, 123))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDfditemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDfditemFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtDfditemFocusLost

    private void txtDaddFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDaddFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtDaddFocusLost

    private void txtDcityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDcityFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtDcityFocusLost

    private void txtDstateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDstateFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtDstateFocusLost

    private void txtDzipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDzipFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtDzipFocusLost

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(!nullCheck()){
            Donation dt= new Donation();
            dt.setDonatId("1");
            dt.setDonatDname(donName);
            dt.setDonatFooditem(txtDfditem.getText());
            dt.setDonatFoodQuant(String.valueOf(sdQuan.getValue()));
            dt.setDonatPickuptype("Pick up");
            dt.setDonatStatus("Requested");
            dt.setDonatWHname(cbWH.getSelectedItem().toString());
            UserAccount ua=new UserAccount();
            ua.setUsername(userAcc.getUsername());
            ua.setPassword(userAcc.getPassword());
            dt.setDonatDonorAcc(ua);
            dt.setDonatAdd(txtDadd.getText());
            dt.setDonatCity(txtDcity.getText());
            donatD = ecosystem.getDonatDirectory();
            donatD.addNewDonation(dt);
            ecosystem.setDonatDirectory(donatD);
            //ecosystem.getDonatDirectory().addNewDonation(dt);
            JOptionPane.showMessageDialog(this, "Your request has been placed. Thank you for your donation!");
            clearfields();
        }
        else{
            JOptionPane.showMessageDialog(this, "Please make sure that you have filled all mandatory fields");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void cbCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCityActionPerformed
        // TODO add your handling code here:
        String city=cbCity.getSelectedItem().toString();
        ArrayList<String> whList = new ArrayList<String>();
        for (FCWarehouse fcw : ecosystem.getFCWDirectory().getFcwList()){
            if(fcw.getFcwCity().equals(city)){
                whList.add(fcw.getFcwName());
            }
        }         
        cbWH.setModel(new DefaultComboBoxModel<String>(whList.toArray(new String[0])));
    }//GEN-LAST:event_cbCityActionPerformed

    private void chkAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAddActionPerformed
        // TODO add your handling code here:
        if(chkAdd.isSelected()){
            for(Donor d: ecosystem.getDonDir().getDonorList()){
                if(d.getDonUserName().equals(donUName)){
                    txtDadd.setText(d.getDonorAddres());
                    txtDcity.setText(d.getDonorCity());
                    txtDstate.setText(d.getDonorState());
                    txtDzip.setText(d.getDonorZipcode());
                }
            }
        }
        else{
            txtDadd.setText("");
            txtDcity.setText("");
            txtDstate.setText("");
            txtDzip.setText("");
        }
    }//GEN-LAST:event_chkAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbCity;
    private javax.swing.JComboBox<String> cbWH;
    private javax.swing.JCheckBox chkAdd;
    private javax.swing.JLabel lblDadd;
    private javax.swing.JLabel lblDcity;
    private javax.swing.JLabel lblDfditem;
    private javax.swing.JLabel lblDfdquan;
    private javax.swing.JLabel lblDfdquan1;
    private javax.swing.JLabel lblDfdquan2;
    private javax.swing.JLabel lblDfdquan3;
    private javax.swing.JLabel lblDfdquan4;
    private javax.swing.JLabel lblDfdquan5;
    private javax.swing.JLabel lblDonProfileTitle;
    private javax.swing.JLabel lblDonProfileTitle1;
    private javax.swing.JLabel lblDstate;
    private javax.swing.JLabel lblDzip;
    private javax.swing.JSlider sdQuan;
    private javax.swing.JTextField txtDadd;
    private javax.swing.JTextField txtDcity;
    private javax.swing.JTextField txtDfditem;
    private javax.swing.JTextField txtDstate;
    private javax.swing.JTextField txtDzip;
    // End of variables declaration//GEN-END:variables

    private boolean nullCheck() {
        if(txtDfditem.getText().length()!=0 && txtDadd.getText().length()!=0 && txtDcity.getText().length()!=0 && 
                txtDstate.getText().length()!=0 && txtDzip.getText().length()!=0 )
        {
            return false;
        }
        else return true;
    }

    private void clearfields() {
        txtDfditem.setText("");
        txtDadd.setText("");
        txtDcity.setText("");
        txtDstate.setText("");
        txtDzip.setText("");
        cbCity.setSelectedIndex(0);
        cbWH.setSelectedIndex(0);
        sdQuan.setExtent(0);
        chkAdd.setSelected(false);
        cbCity.setSelectedIndex(0);
        cbWH.setSelectedIndex(0);
    }
}
