/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package userinterface.FCAdminRole;

import Business.EcoSystem;
import javax.swing.JPanel;

/**
 *
 * @author sowmyachinimilli
 */
public class ManageWHitemsPanel extends javax.swing.JPanel {

    /** Creates new form ManageWHitemsPanel */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    public ManageWHitemsPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPaneWHI = new javax.swing.JSplitPane();
        FCControlPanel = new javax.swing.JPanel();
        btnAddWHI = new javax.swing.JButton();
        btnViewWHI = new javax.swing.JButton();
        FCWorkareaPanel = new javax.swing.JPanel();

        FCControlPanel.setPreferredSize(new java.awt.Dimension(150, 600));

        btnAddWHI.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddWHI.setText("Add Stock");
        btnAddWHI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWHIActionPerformed(evt);
            }
        });

        btnViewWHI.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnViewWHI.setText("View/Update Stock");
        btnViewWHI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewWHIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FCControlPanelLayout = new javax.swing.GroupLayout(FCControlPanel);
        FCControlPanel.setLayout(FCControlPanelLayout);
        FCControlPanelLayout.setHorizontalGroup(
            FCControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FCControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FCControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewWHI, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddWHI, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FCControlPanelLayout.setVerticalGroup(
            FCControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FCControlPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnAddWHI)
                .addGap(26, 26, 26)
                .addComponent(btnViewWHI)
                .addContainerGap(449, Short.MAX_VALUE))
        );

        SplitPaneWHI.setLeftComponent(FCControlPanel);

        FCWorkareaPanel.setPreferredSize(new java.awt.Dimension(840, 600));

        javax.swing.GroupLayout FCWorkareaPanelLayout = new javax.swing.GroupLayout(FCWorkareaPanel);
        FCWorkareaPanel.setLayout(FCWorkareaPanelLayout);
        FCWorkareaPanelLayout.setHorizontalGroup(
            FCWorkareaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
        );
        FCWorkareaPanelLayout.setVerticalGroup(
            FCWorkareaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        SplitPaneWHI.setRightComponent(FCWorkareaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneWHI, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneWHI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddWHIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWHIActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnAddWHIActionPerformed

    private void btnViewWHIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewWHIActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnViewWHIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FCControlPanel;
    private javax.swing.JPanel FCWorkareaPanel;
    private javax.swing.JSplitPane SplitPaneWHI;
    private javax.swing.JButton btnAddWHI;
    private javax.swing.JButton btnViewWHI;
    // End of variables declaration//GEN-END:variables

}
