/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.RequestorRole;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author vipinmamidi
 */
public class RequestorAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestorAreaJPanel
     */
    
     private JPanel userProcessContainer;

    private UserAccount userAccount;
    EcoSystem ecosystem;
    
     public RequestorAreaJPanel(JPanel userProcessContainer, EcoSystem ecosystem, UserAccount account) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
      
        this.userAccount = account;
        this.ecosystem = ecosystem;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPaneReq = new javax.swing.JSplitPane();
        MenubarPanel = new javax.swing.JPanel();
        btnReq = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnStatus = new javax.swing.JButton();
        lblwelname = new javax.swing.JLabel();
        lblWelcomemsg = new javax.swing.JLabel();
        WorkAreaPanel = new javax.swing.JPanel();

        SplitPaneReq.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        btnReq.setBackground(new java.awt.Color(225, 144, 108));
        btnReq.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnReq.setText("Request Food");
        btnReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqActionPerformed(evt);
            }
        });

        btnProfile.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnProfile.setText("My Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnStatus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnStatus.setText("Check Status");
        btnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusActionPerformed(evt);
            }
        });

        lblwelname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblwelname.setText("<value>");

        lblWelcomemsg.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblWelcomemsg.setText("Welcome,");

        javax.swing.GroupLayout MenubarPanelLayout = new javax.swing.GroupLayout(MenubarPanel);
        MenubarPanel.setLayout(MenubarPanelLayout);
        MenubarPanelLayout.setHorizontalGroup(
            MenubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenubarPanelLayout.createSequentialGroup()
                .addGroup(MenubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenubarPanelLayout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(lblWelcomemsg)
                        .addGap(18, 18, 18)
                        .addComponent(lblwelname)
                        .addGap(211, 224, Short.MAX_VALUE))
                    .addGroup(MenubarPanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnProfile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReq)
                        .addGap(232, 232, 232)))
                .addComponent(btnStatus)
                .addGap(73, 73, 73))
        );
        MenubarPanelLayout.setVerticalGroup(
            MenubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenubarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblwelname)
                    .addComponent(lblWelcomemsg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MenubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfile)
                    .addComponent(btnStatus)
                    .addComponent(btnReq))
                .addGap(15, 15, 15))
        );

        SplitPaneReq.setLeftComponent(MenubarPanel);

        WorkAreaPanel.setPreferredSize(new java.awt.Dimension(1000, 700));

        javax.swing.GroupLayout WorkAreaPanelLayout = new javax.swing.GroupLayout(WorkAreaPanel);
        WorkAreaPanel.setLayout(WorkAreaPanelLayout);
        WorkAreaPanelLayout.setHorizontalGroup(
            WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1004, Short.MAX_VALUE)
        );
        WorkAreaPanelLayout.setVerticalGroup(
            WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );

        SplitPaneReq.setRightComponent(WorkAreaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneReq, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneReq, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqActionPerformed
        // TODO add your handling code here:
//        ViewDonationPanel objViewDon = new ViewDonationPanel(userProcessContainer,ecosystem,userAccount);
//        SplitPaneReq.setRightComponent(objViewDon);
    }//GEN-LAST:event_btnReqActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        RequestorProfilePanel objReqProf = new RequestorProfilePanel(userProcessContainer,ecosystem,userAccount);
        SplitPaneReq.setRightComponent(objReqProf);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
        // TODO add your handling code here:
//        DonateNowPanel objDonNow = new DonateNowPanel(userProcessContainer,ecosystem,userAccount);
//        SplitPaneReq.setRightComponent(objDonNow);
    }//GEN-LAST:event_btnStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenubarPanel;
    private javax.swing.JSplitPane SplitPaneReq;
    private javax.swing.JPanel WorkAreaPanel;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnReq;
    private javax.swing.JButton btnStatus;
    private javax.swing.JLabel lblWelcomemsg;
    private javax.swing.JLabel lblwelname;
    // End of variables declaration//GEN-END:variables
}
