/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.RequestorRole;

import Business.EcoSystem;
import Business.Requestor.Requestor;
import Business.Requestor.RequestorDirectory;
import Business.UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sowmyachinimilli
 */
public class RequestorProfilePanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestorProfilePanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAcc;
    String reqUname;
    String reqName;
    RequestorDirectory reqDir;
    public RequestorProfilePanel(JPanel userProcessContainer,EcoSystem ecosystem,UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAcc = userAcc;
        populateFields();
        btnSubmit.setVisible(false);
        lblDpwd1.setVisible(false);
        txtDpwd1.setVisible(false);
        reqUname = userAcc.getUsername();
        reqName = userAcc.getEmployee().getName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDadd = new javax.swing.JTextField();
        lblDadd = new javax.swing.JLabel();
        lblDphno = new javax.swing.JLabel();
        txtDname = new javax.swing.JTextField();
        lblDName = new javax.swing.JLabel();
        lblDonProfileTitle = new javax.swing.JLabel();
        txtDpwd1 = new javax.swing.JTextField();
        lblDpwd1 = new javax.swing.JLabel();
        txtDpwd = new javax.swing.JTextField();
        lblDpwd = new javax.swing.JLabel();
        txtDuname = new javax.swing.JTextField();
        txtDphno = new javax.swing.JTextField();
        lblUname = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        txtDemail = new javax.swing.JTextField();
        lblDemail = new javax.swing.JLabel();
        txtDzip = new javax.swing.JTextField();
        lblDzip = new javax.swing.JLabel();
        txtDstate = new javax.swing.JTextField();
        lblDstate = new javax.swing.JLabel();
        txtDcity = new javax.swing.JTextField();
        lblDcity = new javax.swing.JLabel();
        lblDName1 = new javax.swing.JLabel();
        lblDphno1 = new javax.swing.JLabel();
        lblDadd1 = new javax.swing.JLabel();
        lblDcity1 = new javax.swing.JLabel();
        lblDstate1 = new javax.swing.JLabel();
        lblDzip1 = new javax.swing.JLabel();
        lblDemail1 = new javax.swing.JLabel();
        lblUname1 = new javax.swing.JLabel();
        lblDpwd2 = new javax.swing.JLabel();
        lblDpwd3 = new javax.swing.JLabel();

        txtDadd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDadd.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDadd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDaddFocusLost(evt);
            }
        });

        lblDadd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDadd.setText("Address");

        lblDphno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDphno.setText("Phone Number");

        txtDname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDname.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDnameFocusLost(evt);
            }
        });

        lblDName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDName.setText("Name");

        lblDonProfileTitle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDonProfileTitle.setText("My Food Cloud Profile");

        txtDpwd1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDpwd1.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDpwd1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDpwd1FocusLost(evt);
            }
        });

        lblDpwd1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDpwd1.setText("Confirm Password");

        txtDpwd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDpwd.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDpwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDpwdFocusLost(evt);
            }
        });

        lblDpwd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDpwd.setText("Password");

        txtDuname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDuname.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDuname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDunameFocusLost(evt);
            }
        });

        txtDphno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDphno.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDphno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDphnoFocusLost(evt);
            }
        });

        lblUname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblUname.setText("Username");

        btnEdit.setText("Edit Profile");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        txtDemail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDemail.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDemailFocusLost(evt);
            }
        });

        lblDemail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDemail.setText("Email Id");

        txtDzip.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDzip.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDzip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDzipFocusLost(evt);
            }
        });

        lblDzip.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDzip.setText("Zipcode");

        txtDstate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDstate.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDstate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDstateFocusLost(evt);
            }
        });

        lblDstate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDstate.setText("State");

        txtDcity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDcity.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDcity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDcityFocusLost(evt);
            }
        });

        lblDcity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDcity.setText("City");

        lblDName1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblDphno1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblDadd1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblDcity1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblDstate1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblDzip1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblDemail1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblUname1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblDpwd2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblDpwd3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(lblDonProfileTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEdit)
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblDphno)
                                        .addComponent(lblDadd)
                                        .addComponent(lblDcity)
                                        .addComponent(lblDstate)
                                        .addComponent(lblDzip)
                                        .addComponent(lblDemail)
                                        .addComponent(lblDpwd)
                                        .addComponent(lblDpwd1)
                                        .addComponent(lblDName))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(lblUname)))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDname, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDName1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDphno, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDphno1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDcity, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDcity1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDzip, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDzip1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDemail, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDemail1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDstate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDstate1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDuname, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblUname1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDpwd2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDpwd1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDpwd3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDadd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDadd1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(btnSubmit)))))
                .addContainerGap(375, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblDonProfileTitle)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDName)
                    .addComponent(txtDname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit)
                    .addComponent(lblDName1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDphno)
                    .addComponent(txtDphno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDphno1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDadd)
                    .addComponent(txtDadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDadd1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDcity)
                    .addComponent(txtDcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDcity1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDstate)
                    .addComponent(txtDstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDstate1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDzip)
                    .addComponent(txtDzip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDzip1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDemail)
                    .addComponent(txtDemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDemail1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUname)
                    .addComponent(lblUname1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDpwd)
                    .addComponent(lblDpwd2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDpwd1)
                    .addComponent(txtDpwd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDpwd3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDaddFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDaddFocusLost
        // TODO add your handling code here:
        if(!(txtDadd.getText().matches("^[a-zA-Z]*$"))){
            lblDadd1.setText("Invalid input. Please enter only alphabets");
        }
        else{
            lblDadd1.setText("");
        }
    }//GEN-LAST:event_txtDaddFocusLost

    private void txtDnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDnameFocusLost
        // TODO add your handling code here:
        if(!(txtDname.getText().matches("^[a-zA-Z]*$"))){
            lblDName1.setText("Invalid input. Please enter only alphabets");
        }
        else{
            lblDName1.setText("");
        }
    }//GEN-LAST:event_txtDnameFocusLost

    private void txtDpwd1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDpwd1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDpwd1FocusLost

    private void txtDpwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDpwdFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDpwdFocusLost

    private void txtDunameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDunameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDunameFocusLost

    private void txtDphnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDphnoFocusLost
        // TODO add your handling code here:
        if(!(txtDphno.getText().matches("^[0-9]*$")) || !(txtDphno.getText().length()==10)) {
            lblDphno1.setText("Please enter a valid phone number");
        }
        else{
            lblDphno1.setText("");

        }
    }//GEN-LAST:event_txtDphnoFocusLost

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        enablefields();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(!nullCheck()){
            ArrayList<Requestor> reqList = ecosystem.getReqDir().getReqAccList();
            for(Requestor r: reqList)
            {
                if(r.getReqAccount().getUsername().equals(reqUname))
                {
                    r.setReqName(txtDname.getText());
                    r.setReqPhno(txtDphno.getText());
                    r.setReqEmail(txtDemail.getText());
                    r.setReqAddres(txtDadd.getText());
                    r.setReqCity(txtDcity.getText());
                    r.setReqState(txtDstate.getText());
                    r.setReqZipcode(txtDzip.getText());
                    r.setReqUserName(txtDuname.getText());
                    r.setReqPwd(txtDpwd.getText());
                }
            }
            // ecosystem.setFCWDirectory(fcwList);
            reqDir = ecosystem.getReqDir();
            ecosystem.setReqDir(reqDir);
            JOptionPane.showMessageDialog(this, "Profile updated successfully");
            disableFields();
        }
        else{
            JOptionPane.showMessageDialog(this, "All fields are mandatory!");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtDemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDemailFocusLost
        // TODO add your handling code here:
        if ((!txtDemail.getText().isEmpty()) && !txtDemail.getText().matches("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$")) {
            lblDemail1.setText( "Please Provide Valid Email Address !!");
        }
        else{
            lblDemail1.setText("");
        }
    }//GEN-LAST:event_txtDemailFocusLost

    private void txtDzipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDzipFocusLost
        // TODO add your handling code here:
        if((txtDzip.getText().matches("^[a-zA-Z]*$"))){
            lblDzip1.setText("Invalid input. Please enter only numbers");
        }
        else{
            lblDzip1.setText("");
        }
    }//GEN-LAST:event_txtDzipFocusLost

    private void txtDstateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDstateFocusLost
        // TODO add your handling code here:
        if(!(txtDstate.getText().matches("^[a-zA-Z]*$"))){
            lblDstate1.setText("Invalid input. Please enter only alphabets");
        }
        else{
            lblDstate1.setText("");
        }
    }//GEN-LAST:event_txtDstateFocusLost

    private void txtDcityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDcityFocusLost
        // TODO add your handling code here:
        if(!(txtDcity.getText().matches("^[a-zA-Z]*$"))){
            lblDcity1.setText("Invalid input. Please enter only alphabets");
        }
        else{
            lblDcity1.setText("");
        }
    }//GEN-LAST:event_txtDcityFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblDName;
    private javax.swing.JLabel lblDName1;
    private javax.swing.JLabel lblDadd;
    private javax.swing.JLabel lblDadd1;
    private javax.swing.JLabel lblDcity;
    private javax.swing.JLabel lblDcity1;
    private javax.swing.JLabel lblDemail;
    private javax.swing.JLabel lblDemail1;
    private javax.swing.JLabel lblDonProfileTitle;
    private javax.swing.JLabel lblDphno;
    private javax.swing.JLabel lblDphno1;
    private javax.swing.JLabel lblDpwd;
    private javax.swing.JLabel lblDpwd1;
    private javax.swing.JLabel lblDpwd2;
    private javax.swing.JLabel lblDpwd3;
    private javax.swing.JLabel lblDstate;
    private javax.swing.JLabel lblDstate1;
    private javax.swing.JLabel lblDzip;
    private javax.swing.JLabel lblDzip1;
    private javax.swing.JLabel lblUname;
    private javax.swing.JLabel lblUname1;
    private javax.swing.JTextField txtDadd;
    private javax.swing.JTextField txtDcity;
    private javax.swing.JTextField txtDemail;
    private javax.swing.JTextField txtDname;
    private javax.swing.JTextField txtDphno;
    private javax.swing.JTextField txtDpwd;
    private javax.swing.JTextField txtDpwd1;
    private javax.swing.JTextField txtDstate;
    private javax.swing.JTextField txtDuname;
    private javax.swing.JTextField txtDzip;
    // End of variables declaration//GEN-END:variables

    private void populateFields() {
        for(Requestor r: ecosystem.getReqDir().getReqAccList()){
            txtDname.setText(r.getReqName());
            txtDname.setEnabled(false);
            txtDphno.setText(r.getReqPhno());
            txtDphno.setEnabled(false);
            txtDemail.setText(r.getReqEmail());
            txtDemail.setEnabled(false);
            txtDadd.setText(r.getReqAddres());
            txtDadd.setEnabled(false);
            txtDcity.setText(r.getReqCity());
            txtDcity.setEnabled(false);
            txtDstate.setText(r.getReqState());
            txtDstate.setEnabled(false);
            txtDzip.setText(r.getReqZipcode());
            txtDzip.setEnabled(false);
            txtDuname.setText(r.getReqAccount().getUsername());
            txtDuname.setEnabled(false);
            txtDpwd.setText(r.getReqAccount().getUsername());
            txtDpwd.setEnabled(false);
        } 
    } 

    private void enablefields() {
        txtDname.setEnabled(true);
        txtDphno.setEnabled(true);
        txtDemail.setEnabled(true);
        txtDadd.setEnabled(true);
        txtDcity.setEnabled(true);
        txtDstate.setEnabled(true);
        txtDzip.setEnabled(true);
        txtDuname.setEnabled(true);
        txtDpwd.setEnabled(true);
        btnSubmit.setVisible(true);
        lblDpwd1.setVisible(true);
        txtDpwd1.setVisible(true);
    }

    private boolean nullCheck() {
        if(txtDname.getText().length()!=0 && txtDphno.getText().length()!=0 && txtDemail.getText().length()!=0 
                && txtDadd.getText().length()!=0 && txtDcity.getText().length()!=0 && txtDstate.getText().length()!=0
                && txtDzip.getText().length()!=0 && txtDuname.getText().length()!=0 && txtDpwd.getText().length()!=0
                && txtDpwd1.getText().length()!=0 )
        {
            return false;
        }
        else return true;
    }

    private void disableFields() {
        txtDname.setEnabled(false);
        txtDphno.setEnabled(false);
        txtDemail.setEnabled(false);
        txtDadd.setEnabled(false);
        txtDcity.setEnabled(false);
        txtDstate.setEnabled(false);
        txtDzip.setEnabled(false);
        txtDuname.setEnabled(false);
        txtDpwd.setEnabled(false);
        btnSubmit.setVisible(false);
        lblDpwd1.setVisible(false);
        txtDpwd1.setVisible(false);
        lblDName1.setText("");
        lblDphno1.setText("");
        lblDemail1.setText("");
        lblDadd1.setText("");
        lblDcity1.setText("");
        lblDstate1.setText("");
        lblDzip1.setText("");
        lblUname1.setText("");
        lblDpwd2.setText("");
        lblDpwd3.setText("");
    }
    
}
