/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGORole;

import Business.EcoSystem;
import Business.NGO.NGO;
import Business.NGO.NGODirectory;
import Business.NGOVolunteer.VolunteerDirectory;
import Business.UserAccount.UserAccount;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.DonorRole.DonorProfilePanel;

/**
 *
 * @author aravindasagiraju
 */
public class NGOProfilePanel extends javax.swing.JPanel {

    /**
     * Creates new form NGOProfilePanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    VolunteerDirectory vold;
    UserAccount userAcc;
    NGODirectory ngod;
    String NGOUname;
    boolean validateName = false, validatePhone =false, validateAdd =false, validate; 
    public NGOProfilePanel(JPanel userProcessContainer,EcoSystem ecosystem,UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAcc = userAcc;
        populateFields();
        btnSubmit.setVisible(false);
        lblNGOpwd1.setVisible(false);
        txtNGOpwd1.setVisible(false);
        NGOUname = userAcc.getUsername();
        setBG();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNGOProfileTitle = new javax.swing.JLabel();
        lblNGOName = new javax.swing.JLabel();
        txtNGOname = new javax.swing.JTextField();
        lblNGOphno = new javax.swing.JLabel();
        txtNGOphno = new javax.swing.JTextField();
        lblNGOadd = new javax.swing.JLabel();
        txtNGOadd = new javax.swing.JTextField();
        lblNGOcity = new javax.swing.JLabel();
        txtNGOcity = new javax.swing.JTextField();
        lblNGOstate = new javax.swing.JLabel();
        txtNGOstate = new javax.swing.JTextField();
        lblNGOzip = new javax.swing.JLabel();
        txtNGOzip = new javax.swing.JTextField();
        lblNGOagent = new javax.swing.JLabel();
        txtNGOAgent = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lblUname = new javax.swing.JLabel();
        txtNGOuname = new javax.swing.JTextField();
        lblNGOpwd = new javax.swing.JLabel();
        txtNGOpwd = new javax.swing.JTextField();
        lblNGOpwd1 = new javax.swing.JLabel();
        txtNGOpwd1 = new javax.swing.JTextField();
        lblNGOName1 = new javax.swing.JLabel();
        lblNGOphno1 = new javax.swing.JLabel();
        lblNGOadd1 = new javax.swing.JLabel();
        lblNGOcity1 = new javax.swing.JLabel();
        lblNGOstate1 = new javax.swing.JLabel();
        lblNGOzip1 = new javax.swing.JLabel();
        lblNGOAgent1 = new javax.swing.JLabel();
        lblNGOname1 = new javax.swing.JLabel();
        lblNGOpwd2 = new javax.swing.JLabel();
        lblNGOpwd3 = new javax.swing.JLabel();
        LabelImg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNGOProfileTitle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblNGOProfileTitle.setText("My Profile");
        add(lblNGOProfileTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 23, -1, -1));

        lblNGOName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOName.setText("Name");
        add(lblNGOName, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 81, -1, -1));

        txtNGOname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOname.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOnameFocusLost(evt);
            }
        });
        add(txtNGOname, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 77, 137, -1));

        lblNGOphno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOphno.setText("Phone Number");
        add(lblNGOphno, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 127, -1, -1));

        txtNGOphno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOphno.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOphno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOphnoFocusLost(evt);
            }
        });
        add(txtNGOphno, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 123, 137, -1));

        lblNGOadd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOadd.setText("Address");
        add(lblNGOadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 170, -1, -1));

        txtNGOadd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOadd.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOadd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOaddFocusLost(evt);
            }
        });
        add(txtNGOadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 166, 137, -1));

        lblNGOcity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOcity.setText("City");
        add(lblNGOcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 213, -1, -1));

        txtNGOcity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOcity.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOcity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOcityFocusLost(evt);
            }
        });
        add(txtNGOcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 209, 137, -1));

        lblNGOstate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOstate.setText("State");
        add(lblNGOstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 256, -1, -1));

        txtNGOstate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOstate.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOstate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOstateFocusLost(evt);
            }
        });
        add(txtNGOstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 252, 137, -1));

        lblNGOzip.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOzip.setText("Zipcode");
        add(lblNGOzip, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 299, -1, -1));

        txtNGOzip.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOzip.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOzip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOzipFocusLost(evt);
            }
        });
        add(txtNGOzip, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 295, 137, -1));

        lblNGOagent.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOagent.setText("NGO Agent");
        add(lblNGOagent, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 342, -1, -1));

        txtNGOAgent.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOAgent.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOAgent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOAgentFocusLost(evt);
            }
        });
        add(txtNGOAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 338, 137, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 513, -1, -1));

        btnEdit.setText("Edit Profile");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 76, -1, -1));

        lblUname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblUname.setText("Username");
        add(lblUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 389, -1, -1));

        txtNGOuname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOuname.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOuname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOunameFocusLost(evt);
            }
        });
        add(txtNGOuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 381, 137, -1));

        lblNGOpwd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOpwd.setText("Password");
        add(lblNGOpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 428, -1, -1));

        txtNGOpwd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOpwd.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOpwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOpwdFocusLost(evt);
            }
        });
        add(txtNGOpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 424, 137, -1));

        lblNGOpwd1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNGOpwd1.setText("Confirm Password");
        add(lblNGOpwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 471, -1, -1));

        txtNGOpwd1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNGOpwd1.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOpwd1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOpwd1FocusLost(evt);
            }
        });
        txtNGOpwd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNGOpwd1ActionPerformed(evt);
            }
        });
        add(txtNGOpwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 467, 137, -1));

        lblNGOName1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 76, -1, -1));

        lblNGOphno1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOphno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 123, -1, -1));

        lblNGOadd1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOadd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 166, -1, -1));

        lblNGOcity1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOcity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 209, -1, -1));

        lblNGOstate1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOstate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 252, -1, -1));

        lblNGOzip1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOzip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 295, -1, -1));

        lblNGOAgent1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOAgent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 338, -1, -1));

        lblNGOname1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 381, -1, -1));

        lblNGOpwd2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOpwd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 424, -1, -1));

        lblNGOpwd3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOpwd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 467, -1, -1));
        add(LabelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, -4, 1690, 900));
    }// </editor-fold>//GEN-END:initComponents

    public void setBG() {
        try {
            LabelImg.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/blurbg.jpeg"));

            Image newimg = img.getScaledInstance(1750, 950, java.awt.Image.SCALE_SMOOTH);
            LabelImg.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(NGOProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void txtNGOnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOnameFocusLost
        // TODO add your handling code here:
        if(!(txtNGOname.getText().matches("^[a-zA-Z]*$"))){
            lblNGOName1.setText("Invalid input. Please enter only alphabets");
        }
        else{
            lblNGOName1.setText("");
        }
    }//GEN-LAST:event_txtNGOnameFocusLost

    private void txtNGOphnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOphnoFocusLost
        // TODO add your handling code here:
        if(!(txtNGOphno.getText().matches("^[0-9]*$")) || !(txtNGOphno.getText().length()==10)) {
            lblNGOphno1.setText("Please enter a valid phone number");
        }
        else{
            lblNGOphno1.setText("");

        }
    }//GEN-LAST:event_txtNGOphnoFocusLost

    private void txtNGOaddFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOaddFocusLost
        // TODO add your handling code here:
        if(!(txtNGOadd.getText().matches("^[a-zA-Z]*$"))){
            lblNGOadd1.setText("Invalid input. Please enter only alphabets");
        }
        else{
            lblNGOadd1.setText("");
        }
    }//GEN-LAST:event_txtNGOaddFocusLost

    private void txtNGOcityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOcityFocusLost
        // TODO add your handling code here:
        if(!(txtNGOcity.getText().matches("^[a-zA-Z]*$"))){
            lblNGOcity1.setText("Invalid input. Please enter only alphabets");
        }
        else{
            lblNGOcity1.setText("");
        }
    }//GEN-LAST:event_txtNGOcityFocusLost

    private void txtNGOstateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOstateFocusLost
        // TODO add your handling code here:
        if(!(txtNGOstate.getText().matches("^[a-zA-Z]*$"))){
            lblNGOstate1.setText("Invalid input. Please enter only alphabets");
        }
        else{
            lblNGOstate1.setText("");
        }
    }//GEN-LAST:event_txtNGOstateFocusLost

    private void txtNGOzipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOzipFocusLost
        // TODO add your handling code here:
        if((txtNGOzip.getText().matches("^[a-zA-Z]*$"))){
            lblNGOzip1.setText("Invalid input. Please enter only numbers");
        }
        else{
            lblNGOzip1.setText("");
        }
    }//GEN-LAST:event_txtNGOzipFocusLost

    private void txtNGOAgentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOAgentFocusLost
        // TODO add your handling code here:
        if ((!txtNGOAgent.getText().isEmpty()) && !txtNGOAgent.getText().matches("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$")) {
            lblNGOAgent1.setText( "Please Provide Valid Email Address !!");
        }
        else{
            lblNGOAgent1.setText("");
        }
    }//GEN-LAST:event_txtNGOAgentFocusLost

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(!nullCheck()){
            ArrayList<NGO> ngoList = ecosystem.getNgoDir().getNgoList();
            for(NGO d: ngoList)
            {
                if(d.getNgoAccount().getUsername().equals(NGOUname))
                {
                    d.setNgoName(txtNGOname.getText());
                    d.setNgoPhno(txtNGOphno.getText());
                    d.setNgoAgent(txtNGOAgent.getText());
                    d.setNgoAddress(txtNGOadd.getText());
                    d.setNgoCity(txtNGOcity.getText());
                    d.setNgoState(txtNGOstate.getText());
                    d.setNgoZipcode(txtNGOzip.getText());
                    UserAccount ngoAccount=new UserAccount();
                    ngoAccount.setUsername(txtNGOuname.getText());
                    ngoAccount.setPassword(txtNGOpwd.getText());
                }
            }
            // ecosystem.setFCWDirectory(fcwList);
            ngod = ecosystem.getNgoDir();
            ecosystem.setNgoDir(ngod);
            JOptionPane.showMessageDialog(this, "Profile updated successfully");
            disableFields();
        }
        else{
            JOptionPane.showMessageDialog(this, "All fields are mandatory!");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        enablefields();
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtNGOunameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOunameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNGOunameFocusLost

    private void txtNGOpwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOpwdFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNGOpwdFocusLost

    private void txtNGOpwd1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOpwd1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNGOpwd1FocusLost

    private void txtNGOpwd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNGOpwd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNGOpwd1ActionPerformed

    private void populateFields() {
        for(NGO d: ecosystem.getNgoDir().getNgoList()){
            txtNGOname.setText(d.getNgoName());
            txtNGOname.setEnabled(false);
            txtNGOphno.setText(d.getNgoPhno());
            txtNGOphno.setEnabled(false);
            txtNGOAgent.setText(d.getNgoAgent());
            txtNGOAgent.setEnabled(false);
            txtNGOadd.setText(d.getNgoAddress());
            txtNGOadd.setEnabled(false);
            txtNGOcity.setText(d.getNgoCity());
            txtNGOcity.setEnabled(false);
            txtNGOstate.setText(d.getNgoState());
            txtNGOstate.setEnabled(false);
            txtNGOzip.setText(d.getNgoZipcode());
            txtNGOzip.setEnabled(false);
            txtNGOuname.setText(d.getNgoAccount().getUsername());
            txtNGOuname.setEnabled(false);
            txtNGOpwd.setText(d.getNgoAccount().getPassword());
            txtNGOpwd.setEnabled(false);
        }
    }
    
    private void enablefields() {
        txtNGOname.setEnabled(true);
        txtNGOphno.setEnabled(true);
        txtNGOAgent.setEnabled(true);
        txtNGOadd.setEnabled(true);
        txtNGOcity.setEnabled(true);
        txtNGOstate.setEnabled(true);
        txtNGOzip.setEnabled(true);
        txtNGOuname.setEnabled(true);
        txtNGOpwd.setEnabled(true);
        btnSubmit.setVisible(true);
        lblNGOpwd1.setVisible(true);
        txtNGOpwd1.setVisible(true);
    }
    
    private void disableFields() {
        txtNGOname.setEnabled(false);
        txtNGOphno.setEnabled(false);
        txtNGOAgent.setEnabled(false);
        txtNGOadd.setEnabled(false);
        txtNGOcity.setEnabled(false);
        txtNGOstate.setEnabled(false);
        txtNGOzip.setEnabled(false);
        txtNGOuname.setEnabled(false);
        txtNGOpwd.setEnabled(false);
        btnSubmit.setVisible(false);
        lblNGOpwd1.setVisible(false);
        txtNGOpwd1.setVisible(false);
        lblNGOName1.setText("");
        lblNGOphno1.setText("");
        lblNGOAgent1.setText("");
        lblNGOadd1.setText("");
        lblNGOcity1.setText("");
        lblNGOstate1.setText("");
        lblNGOzip1.setText("");
        lblNGOname1.setText("");
        lblNGOpwd2.setText("");
        lblNGOpwd3.setText("");
    }
 
    private boolean nullCheck() {
        if(txtNGOname.getText().length()!=0 && txtNGOphno.getText().length()!=0 && txtNGOAgent.getText().length()!=0 
                && txtNGOadd.getText().length()!=0 && txtNGOcity.getText().length()!=0 && txtNGOstate.getText().length()!=0
                && txtNGOzip.getText().length()!=0 && txtNGOuname.getText().length()!=0 && txtNGOpwd.getText().length()!=0
                && txtNGOpwd1.getText().length()!=0 )
        {
            return false;
        }
        else return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImg;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblNGOAgent1;
    private javax.swing.JLabel lblNGOName;
    private javax.swing.JLabel lblNGOName1;
    private javax.swing.JLabel lblNGOProfileTitle;
    private javax.swing.JLabel lblNGOadd;
    private javax.swing.JLabel lblNGOadd1;
    private javax.swing.JLabel lblNGOagent;
    private javax.swing.JLabel lblNGOcity;
    private javax.swing.JLabel lblNGOcity1;
    private javax.swing.JLabel lblNGOname1;
    private javax.swing.JLabel lblNGOphno;
    private javax.swing.JLabel lblNGOphno1;
    private javax.swing.JLabel lblNGOpwd;
    private javax.swing.JLabel lblNGOpwd1;
    private javax.swing.JLabel lblNGOpwd2;
    private javax.swing.JLabel lblNGOpwd3;
    private javax.swing.JLabel lblNGOstate;
    private javax.swing.JLabel lblNGOstate1;
    private javax.swing.JLabel lblNGOzip;
    private javax.swing.JLabel lblNGOzip1;
    private javax.swing.JLabel lblUname;
    private javax.swing.JTextField txtNGOAgent;
    private javax.swing.JTextField txtNGOadd;
    private javax.swing.JTextField txtNGOcity;
    private javax.swing.JTextField txtNGOname;
    private javax.swing.JTextField txtNGOphno;
    private javax.swing.JTextField txtNGOpwd;
    private javax.swing.JTextField txtNGOpwd1;
    private javax.swing.JTextField txtNGOstate;
    private javax.swing.JTextField txtNGOuname;
    private javax.swing.JTextField txtNGOzip;
    // End of variables declaration//GEN-END:variables
}
